name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: list and read file
          run: |
           echo "my first github action"
           ls -ltra
           cat README.md

        # - name: list file
        #   run: ls -ltr

        # - name: read file
        #   run: cat README.md
          
            