name: matrix configuration
on:
    push:
    workflow_dispatch: 

jobs:
    deploy:
      strategy:
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, window-latest]
          image: [hello-world, apline]
      runs-on: ${{ matrix }}
      steps:
      - name: echo docker details
        run: docker info

      - name: run image on ${{ matrix.os }}
        run: docker run ${{matrix.image }}